### ISSUE TITLE
代码实施问题，embed_net返回值个数不对

### ISSUE THREAD

**Issue by ReIDkj** [hanzhengwang/DFLN-ViT#1]
在实施代码的过程中，报错：
File "train.py", line 306, in train
    outputs, feat, Loss = net(input1, input2)
ValueError: not enough values to unpack (expected 3, got 2)
发现是调用embed_net的返回值时错误，在training中embed_net返回的值只有两个，而training中用到的值却有三个：
outputs, feat, Loss = net(input1, input2)
想问一下作者这里应该怎么解决，万分感谢！

**Comment by hanzhengwang** [comment]
你好，已更新训练代码。

**Comment by hanzhengwang** [comment]
你好，已更新训练代码。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hanzhengwang/DFLN-ViT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 晚上7:48
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[hanzhengwang/DFLN-ViT] 代码实施问题，embed_net返回值个数不对 (Issue #1)





 
在实施代码的过程中，报错：
 File "train.py", line 306, in train
 outputs, feat, Loss = net(input1, input2)
 ValueError: not enough values to unpack (expected 3, got 2)
 发现是调用embed_net的返回值时错误，在training中embed_net返回的值只有两个，而training中用到的值却有三个：
 outputs, feat, Loss = net(input1, input2)
 想问一下作者这里应该怎么解决，万分感谢！
